# Generated by Django 5.1.2 on 2024-10-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('legenda', models.CharField(max_length=200)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('data_actualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
