# Generated by Django 5.1.2 on 2024-10-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_utilizador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='utilizador',
        ),
    ]
